added env check for required binaries

diff --git a/mlvdsel b/mlvdsel
--- a/mlvdsel
+++ b/mlvdsel
@@ -37,6 +37,12 @@ ask_one_of() {
   done
 }
 
+# CHECK REQUIREMENTS
+# ------------------
+for binary in wg-quick systemctl sudo; do
+  which "$binary" &>/dev/null || die "Required '$binary' is not available."
+done
+
 # OPTION PARSING
 # --------------
 
diff --git a/prtscn b/prtscn
--- a/prtscn
+++ b/prtscn
@@ -1,4 +1,12 @@
 #!/bin/bash
+die() {
+  echo "$@"
+  exit 1
+}
+
+for binary in maim notify-send xdotool; do
+  which "$binary" &>/dev/null || die "Required '$binary' is not available."
+done
 
 output_dir="$HOME/Pictures/screenshots"
 output="$output_dir/$(date +'%Y-%m-%d-%H%M%S').png"
@@ -7,12 +15,12 @@ source=''
 
 mkdir -p "$output_dir"
 while getopts rcw opt; do
-    case $opt in
-        r) ;;
-        w) source="-i $(xdotool getactivewindow)" ;;
-        c) source="-s -c $color";;
-        \?) echo "Invalid option: -$OPTARG"; exit ;;
-    esac
+  case $opt in
+    r) ;;
+    w) source="-i $(xdotool getactivewindow)" ;;
+    c) source="-s -c $color";;
+    \?) die "Invalid option: -$OPTARG" ;;
+  esac
 done
 
 maim "$source" "$output" &&
diff --git a/recscn b/recscn
--- a/recscn
+++ b/recscn
@@ -1,7 +1,10 @@
 #!/bin/bash
+for binary in ffcast ffmpeg notify-send; do
+  which "$binary" &>/dev/null || die "Required '$binary' is not available."
+done
 
 output_dir="$HOME/Video/capture"
-output="$output_dir"/`date +'%Y-%m-%d-%H%M%S'`.webm
+output="$output_dir"/$(date +'%Y-%m-%d-%H%M%S').webm
 color=1,1,1,0.1
 source=''
 
diff --git a/thumbnailer b/thumbnailer
--- a/thumbnailer
+++ b/thumbnailer
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+die() { echo "$@"; exit 1; }
+
 min() { [ "$1" -lt "$2" ] && echo "$1" || echo "$2"; }
 
 extension() { basename "$1" | sed -e 's/^.*\.\([^\.]*\)$/\L\1/'; }
@@ -29,18 +31,22 @@ gen_thumb() {
   fi
 }
 
+for binary in ffmpegthumbnailer convert; do
+  which "$binary" &>/dev/null || die "Required '$binary' is not available."
+done
+
 CACHE="$HOME/.cache/thumbs"
 MAX_W=400
 MAX_H=400
 
 if ! ( match_vid_ext "$1" || match_img_ext "$1" ); then
-  echo "Extension not supported"; exit 1
+  die "Extension not supported"
 fi
 
 while [ "${1:0:1}" = "-" ]; do
   case "${1:1}" in
     path) cache_path "$2"; exit 0 ;;
-    *) echo "Option not supported"; exit 1 ;;
+    *) die "Option not supported" ;;
   esac
   shift
 done
